import bcrypt from 'bcryptjs';


const data = {

    users: [
        {
            name: 'ThongAdmin',
            email: 'thongadmin@gmail.com',
            password: bcrypt.hashSync('123456', 8),
            isAdmin: true,
        },
        {
            name: 'Store 01',
            email: 'store01@gmail.com',
            password: bcrypt.hashSync('123456', 8),
            isAdmin: false,
            isSeller: true,
            seller: {
                name: 'Store 1',
                logo: 'images/carouselImg01.jpg',
                description: 'Ho Chi Minh',
                rating: 5.0,
                numReviews: 19,
            }
        },
        {
            name: 'Store 02',
            email: 'store02@gmail.com',
            password: bcrypt.hashSync('123456', 8),
            isAdmin: false,
            isSeller: true,
            seller: {
                name: 'Store 2',
                logo: 'images/carouselImg02.jpg',
                description: 'Ha Noi',
                rating: 5.0,
                numReviews: 19,
            }
        },
        {
            name: 'Store 03',
            email: 'store03@gmail.com',
            password: bcrypt.hashSync('123456', 8),
            isAdmin: false,
            isSeller: true,
            seller: {
                name: 'Store 3',
                logo: 'images/carouselImg03.jpg',
                description: 'Da Nang',
                rating: 5.0,
                numReviews: 19,
            }
        },
        {
            name: 'ThongUser1',
            email: 'thong1@gmail.com',
            password: bcrypt.hashSync('123456', 8),
            isAdmin: false,
        },
    ],

    products: [
        {
            name: 'Berin Blue Shirt',
            category: 'Shirts',
            image: '/images/Shirts/shirt01.jpg',
            price: 70,
            countInStock: 10,
            brand: 'Chuong Talor',
            rating: 0,
            numReviews: 0,
            description: 'Cotton fabric is soft and comfortable. Berin green color for youthful, outstanding style. Fabric design in collar and sleeves.',
        },
        {
            name: 'Solid Yellow Shirt',
            category: 'Shirts',
            image: '/images/Shirts/shirt02.jpg',
            price: 70,
            countInStock: 5,
            brand: 'Chuong Talor',
            rating: 0,
            numReviews: 0,
            description: 'Comfortable, breathable cotton fabric for Spring Summer. Solid yellow color for youthful, outstanding style.',
        },
        {

            name: 'White Polka Dot Shirt',
            category: 'Shirts',
            image: '/images/Shirts/shirt03.jpg',
            price: 70,
            countInStock: 10,
            brand: 'Chuong Talor',
            rating: 0,
            numReviews: 0,
            description: 'Preferred cotton material for shirts. Dark blue-violet fabric color is easy to match with the majority and coordinate outfits.',
        },
        {

            name: 'Red Earth Shirt',
            category: 'Shirts',
            image: '/images/Shirts/shirt04.jpg',
            price: 70,
            countInStock: 10,
            brand: 'Chuong Tator',
            rating: 0,
            numReviews: 0,
            description: 'Sewn from soft and breathable cotton fabric. Designed with a basic shape and a small, modern, youthful collar.',
        },
        {

            name: 'White Blue Plaid Shirt',
            category: 'Shirts',
            image: '/images/Shirts/shirt05.jpg',
            price: 129,
            countInStock: 10,
            brand: 'Chuong Tator',
            rating: 0,
            numReviews: 0,
            description: 'Blue and white plaid pattern for a striking shirt that is still simple, for a masculine and strong style.',
        },
        {
            name: 'White Blue Polka Dot Shirt',
            category: 'Shirts',
            image: '/images/Shirts/shirt06.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Chuong Talor',
            rating: 0,
            numReviews: 0,
            description: 'Basic white color combined with microscopic blue dot pattern creates an elegant and youthful shirt.',
        },
        {
            name: 'Gray Bold White Suit',
            category: 'Suits',
            image: '/images/Suits/suit01.jpg',
            price: 300,
            countInStock: 5,
            brand: 'Chuong Talor',
            rating: 0,
            numReviews: 0,
            description: 'High Quality Suit.',
        },
        {
            name: 'Gray White Suit',
            category: 'Suits',
            image: '/images/Suits/suit02.jpg',
            price: 300,
            countInStock: 5,
            brand: 'Chuong Talor',
            rating: 0,
            numReviews: 0,
            description: 'High Quality Suit.',
        },
        {
            name: 'Black Suit',
            category: 'Suits',
            image: '/images/Suits/suit03.jpg',
            price: 300,
            countInStock: 5,
            brand: 'Chuong Talor',
            rating: 0,
            numReviews: 0,
            description: 'High Quality Suit.',
        },
        {
            name: 'Regular Black Suit',
            category: 'Suits',
            image: '/images/Suits/suit04.jpg',
            price: 300,
            countInStock: 5,
            brand: 'Chuong Talor',
            rating: 0,
            numReviews: 0,
            description: 'High Quality Suit.',
        },
        {
            name: 'Regular Gray Suit',
            category: 'Suits',
            image: '/images/Suits/suit05.jpg',
            price: 300,
            countInStock: 5,
            brand: 'Chuong Talor',
            rating: 0,
            numReviews: 0,
            description: 'High Quality Suit.',
        },
        {
            name: 'Blue Suit',
            category: 'Suits',
            image: '/images/Suits/suit06.jpg',
            price: 300,
            countInStock: 5,
            brand: 'Chuong Talor',
            rating: 0,
            numReviews: 0,
            description: 'High Quality Suit.',
        },
        {
            name: 'Blue Demi Cerruti',
            category: 'Jackets',
            image: '/images/Jackets/jacket01.jpg',
            price: 250,
            countInStock: 5,
            brand: 'Chuong Talor',
            rating: 0,
            numReviews: 0,
            description: 'Composition: 100% wool, Weave: 2/2 twill.',
        },
        {
            name: 'Striped Maroon Demi',
            category: 'Jackets',
            image: '/images/Jackets/jacket02.jpg',
            price: 250,
            countInStock: 5,
            brand: 'Chuong Talor',
            rating: 0,
            numReviews: 0,
            description: 'Composition: 90% wool, 10% polyester.',
        },
        {
            name: 'Blue Dark Demi',
            category: 'Jackets',
            image: '/images/Jackets/jacket03.jpg',
            price: 250,
            countInStock: 5,
            brand: 'Chuong Talor',
            rating: 0,
            numReviews: 0,
            description: 'Composition: 100 % wool, Weave: 2/2 twill.',
        },
        {
            name: 'Windowpane Blue Demi',
            category: 'Jackets',
            image: '/images/Jackets/jacket04.jpg',
            price: 250,
            countInStock: 5,
            brand: 'Chuong Talor',
            rating: 0,
            numReviews: 0,
            description: '100% Luxury Merino Wool.',
        },
        {
            name: 'Regular Windowpane Blue Demi',
            category: 'Jackets',
            image: '/images/Jackets/jacket05.jpg',
            price: 250,
            countInStock: 5,
            brand: 'Chuong Talor',
            rating: 0,
            numReviews: 0,
            description: '100% Luxury Merino Wool.',
        },
        {
            name: 'Brown Demi',
            category: 'Jackets',
            image: '/images/Jackets/jacket06.jpg',
            price: 250,
            countInStock: 5,
            brand: 'Chuong Talor',
            rating: 0,
            numReviews: 0,
            description: '100% Luxury Merino Wool.',
        },
        {
            name: 'Gray Waistcoats',
            category: 'Waistcoats',
            image: '/images/Waistcoats/waistcoats01.jpg',
            price: 270,
            countInStock: 5,
            brand: 'Chuong Talor',
            rating: 0,
            numReviews: 0,
            description: 'High Quality Product.',
        },
        {
            name: 'Black Blue Outerwear',
            category: 'Outerwear',
            image: '/images/Outerwear/outerwear01.jpg',
            price: 500,
            countInStock: 5,
            brand: 'Chuong Talor',
            rating: 0,
            numReviews: 0,
            description: 'High Quality Product.',
        },
        {
            name: 'Golden Outerwear',
            category: 'Outerwear',
            image: '/images/Outerwear/outerwear02.jpg',
            price: 600,
            countInStock: 5,
            brand: 'Chuong Talor',
            rating: 0,
            numReviews: 0,
            description: 'High Quality Product.',
        },
        {
            name: 'Gray Outerwear',
            category: 'Outerwear',
            image: '/images/Outerwear/outerwear03.jpg',
            price: 600,
            countInStock: 5,
            brand: 'Chuong Talor',
            rating: 0,
            numReviews: 0,
            description: 'High Quality Product.',
        },
    ]
}

export default data;